# Generated automatically from Makefile.in by configure.
VPATH = /root/cs161/cs161-gdb-1.4/./gdb-6.0+cs161/gdb/testsuite/gdb.objc
srcdir = /root/cs161/cs161-gdb-1.4/./gdb-6.0+cs161/gdb/testsuite/gdb.objc

EXECUTABLES = basicclass

all: 
	@echo "Nothing to be done for all..."

info:
install-info:
dvi:
install:
uninstall: force
installcheck:
check:

clean mostlyclean:
	-rm -f *~ *.o *.ci
	-rm -f core ${EXECUTABLES}

distclean maintainer-clean realclean: clean
	-rm -f Makefile config.status config.log
