# Generated automatically from Makefile.in by configure.
VPATH = /root/cs161/cs161-gdb-1.4/./gdb-6.0+cs161/gdb/testsuite/gdb.mi
srcdir = /root/cs161/cs161-gdb-1.4/./gdb-6.0+cs161/gdb/testsuite/gdb.mi

PROGS = basics c_variable cpp_variable var-cmd

MISCELLANEOUS = testcmds

all info install-info dvi install uninstall installcheck check:
	@echo "Nothing to be done for $@..."

clean mostlyclean:
	-rm -f *.ci *.o $(OBJS) $(PROGS) *~ core

distclean maintainer-clean realclean: clean
	-rm -f Makefile config.status config.log
