Script started on Fri 05 Sep 2014 06:23:12 PM EDT
]0;root@comp:~/cs161[?1034h[root@comp cs161]# cd ~/cs161/root
]0;root@comp:~/cs161/root[root@comp root]# ./sys161 -w kernel
sys161: System/161 release 1.14, compiled Sep  5 2014 18:21:06
sys161: Waiting for debugger connection...
sys161: New debugger connection

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #6)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

Hello World
OS/161 kernsys161: gdbcomm: read: EOF from debugger
el [? for menu]: exit
Shutting down.
The system is halted.
sys161: 1532864213 cycles (11286074k, 0u, 1521578139i)
sys161: 6668 irqs 0 exns 0r/0w disk 5r/595w console 0r/0w/1m emufs 0r/0w net
sys161: Elapsed real time: 36.111194 seconds (42.4485 mhz)
sys161: Elapsed virtual time: 61.314568480 seconds (25 mhz)
]0;root@comp:~/cs161/root[root@comp root]# exit
exit

Script done on Fri 05 Sep 2014 06:24:45 PM EDT
