Script started on Thu 04 Sep 2014 07:39:06 PM EDT
]0;root@comp:~/cs161[?1034h[root@comp cs161]# cd d[Kroot/
]0;root@comp:~/cs161/root[root@comp root]# ./sys161 kernel
sys161: System/161 release 1.12, compiled Sep  4 2014 18:34:28

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p/bbnn/oeeooff<rttrr>[[D[[D[[D[A
]0;root@comp:~/cs161/root[root@comp root]# ./sys161 kernel
sys161: System/161 release 1.12, compiled Sep  4 2014 18:34:28

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/poweroff/      f <return>
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 666253169 cycles (6494123k, 19u, 659759027i)
sys161: 3317 irqs 6 exns 0r/0w disk 35r/683w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 26.647830 seconds (25.0022 mhz)
sys161: Elapsed virtual time: 26.650126760 seconds (25 mhz)
]0;root@comp:~/cs161/root[root@comp root]# exit
exit

Script done on Thu 04 Sep 2014 07:40:34 PM EDT
